// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpiK_7kHCN31AtnaeJDDLGNrDpu6NUItg',
    appId: '1:789658493024:web:8830d2977a4d98857c2305',
    messagingSenderId: '789658493024',
    projectId: 'ilililil-9dde0',
    authDomain: 'ilililil-9dde0.firebaseapp.com',
    storageBucket: 'ilililil-9dde0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-u0WxB8KYWQlVuWmowmedScJeKN9hI7A',
    appId: '1:789658493024:android:308ca8b3597adc877c2305',
    messagingSenderId: '789658493024',
    projectId: 'ilililil-9dde0',
    storageBucket: 'ilililil-9dde0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWyFDP9Em13LaQ79mENIuEZbx2e5af5Gc',
    appId: '1:789658493024:ios:8077ea490c6d10087c2305',
    messagingSenderId: '789658493024',
    projectId: 'ilililil-9dde0',
    storageBucket: 'ilililil-9dde0.appspot.com',
    iosClientId: '789658493024-5645i8fmstsggh777gosi288bd3aerun.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWyFDP9Em13LaQ79mENIuEZbx2e5af5Gc',
    appId: '1:789658493024:ios:8077ea490c6d10087c2305',
    messagingSenderId: '789658493024',
    projectId: 'ilililil-9dde0',
    storageBucket: 'ilililil-9dde0.appspot.com',
    iosClientId: '789658493024-5645i8fmstsggh777gosi288bd3aerun.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFirebaseCrud',
  );
}
